---
title: "Slide Prep"
date: last-modified
date-format: "dddd, DD/MM/YYYY"
format: 
  html:
    theme: flatly
    code-fold: true
    code-copy: hover
    code-overflow: wrap
    code-tools: true
    df-print: paged
    default-image-extension: svg
    embed-resources: true
    page-layout: full
    reference-location: margin
    title-block-banner: true
    title-block-style: default
    fontsize: .9em
    monofont: 'Fira Code'
execute: 
  echo: true
  warning: true
number-sections: true
toc: true
fig-dpi: 320
dpi: 320
---

# Setup

```{r}
#| label: setup

options(scipen = 999)
pacman::p_load(tidyverse, haven, labelled, arrow, simstudy, survey)

pop_dist <- read_parquet("https://storage.dosm.gov.my/population/population_district.parquet")

selsimds0 <- read_sav("20240926_SelSimData.sav")
selsimds <- selsimds0 %>% 
  to_factor()
  
```

```{r}
pop_dist %>% 
  distinct(state)
```


```{r}
set.seed(121)
selected_district <- pop_dist %>% 
  distinct(state, district) %>% 
  mutate(zone = case_when(state %in% c("Johor", "Melaka", 
                                      "Negeri Sembilan") ~ "Selatan", 
                         state %in% c("Kedah", "Perak", 
                                      "Perlis", "Pulau Pinang") ~ "Utara", 
                         state %in% c("Kelantan", "Pahang", 
                                      "Terengganu") ~ "Timur", 
                         state %in% c("Selangor", "W.P. Kuala Lumpur", 
                                      "W.P. Putrajaya") ~ "Tengah", 
                         state %in% c("Sabah", "Sarawak", 
                                      "W.P. Labuan") ~ "Borneo")) %>% 
  group_by(zone) %>% 
  slice_sample(n = 2) %>% 
  ungroup() %>% 
  relocate(zone, .before = 1)

selected_district

write_rds(selected_district, "selected_district.rds")
```

